- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxSilly
  - CorvaxAstra
  - CorvaxMaus
  - CorvaxPaper
  - CorvaxPilgrim
  - CorvaxTerra
  - CorvaxPearl
  - NanoStation
  - Atlas
  - Bagel
  - Box
  - Core
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Saltern
  - Packed
  - Train
