- type: gameMapPool
  id: CorvaxDefaultMapPool
  maps:
  # Highpop
  - CorvaxDelta
  - CorvaxAvrite
  - CorvaxAstra
  - CorvaxPilgrim
<<<<<<< HEAD
  - CorvaxTerra
  - CorvaxPearl
  - NanoStation
  - CorvaxTushkan
=======
>>>>>>> b8a0e0de0b16e2cb37a91cafab7bc2dbf85667d3
  - CorvaxGlacier
  - Box
  # Midpop
  - CorvaxPaper
  - CorvaxPearl
  - Bagel
  - Marathon
  #- Train
  # Lowpop
  - CorvaxSilly
  - CorvaxMaus
  - CorvaxTushkan
  - Packed
  - Omega
