name: Delete artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'

    - uses: geekyeggo/delete-artifact@v5
      if: always()
      with:
        name: build
